name: modulife
description: "Simply an easier life."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.2.0

repository: https://github.com/Mnov34/ModuLife
homepage: https://github.com/Mnov34/ModuLife
issue_tracker: https://github.com/Mnov34/ModuLife/issues

platforms:
  android:
  ios: #NOT TESTED YET

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^9.2.2
  logger: ^2.4.0
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.2
  formz: ^0.7.0
  uuid: ^4.5.0

  modulife_ui_colors:
    path: packages/modulife_ui_colors
  modulife_utils:
    path: packages/modulife_utils

  modulife_todos:
    path: packages/modulife_todos
  modulife_notes:
    path: packages/modulife_notes

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11


flutter:
  uses-material-design: true

  assets:
   - assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

funding:
  - https://www.patreon.com/MNov34
  - https://buymeacoffee.com/mnov34